version: '3'
services:  
  mongo:
    image: mongo:latest
    container_name: mongo
    environment: 
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/log
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
  api:
    build: ./app
    image: app:yawoen
    restart: always
    container_name: api
    ports:
      - 5000:5000
    depends_on:
      - mongo